### ISSUE TITLE
有的时候代理会失效

### ISSUE THREAD

**Issue by TDL3** [CGDF-Github/SSD-Windows#13]
之前一直是用的是SSR, 一直没遇到这个问题， 最近换到SSD有时候会莫名其妙的断开链接，重启SSD没有效果，解决办法通常是重新拨号连接，或者netsh winsock reset， 不太确定如何重现这个问题

**Comment by TDL3** [comment]
原版Shadowsocks-windows没有发现这个问题

**Comment by CGDF-Github** [comment]
@TDL3 也许log可以看出点东西？

**Comment by TDL3** [comment]
发现问题了，我把敏感信息去掉了

//代理失效时的错误信息，此时可以访国内的网站，无法访问被封锁的网站
[2019-01-01 16:40:42] **HOST NAME** (**IP ADDRESS**:4503) timed out
[2019-01-01 16:41:30] System.Net.Sockets.SocketException (0x80004005): A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at Shadowsocks.Controller.TCPHandler.PipeRemoteSendCallback(IAsyncResult ar)

//重新拨号连接后出现的信息，此时能正常使用代理
[2019-01-01 16:43:24] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-01 16:43:24] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-01 16:43:24] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-01 16:43:25] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-01 16:43:25] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by TDL3** [comment]
我试过的节点都有这个问题QAQ

**Comment by TDL3** [comment]
//发生在之前的一次错误，错误信息貌似不太一样
[2018-12-31 20:17:19] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-12-31 20:17:19] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2018-12-31 20:17:19] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by TDL3** [comment]
又出了新的问题QAQ
![capture](https://user-images.githubusercontent.com/29535697/50842377-82679680-13a1-11e9-96dc-7474b37af87d.PNG)

**Comment by CGDF-Github** [comment]
触发条件是？

**Comment by TDL3** [comment]
我当时是发现代理失效了，重新拨号连接无效，我尝试切换节点，就这样了。

**Comment by CGDF-Github** [comment]
“原版SS没有发现这个问题”是试了多久得出的结论？我实在想确认一下

**Comment by TDL3** [comment]
一天吧。可是我在用SSR之前一直在用SS啊，真的没遇到过这个问题

**Comment by TDL3** [comment]
所以这个问题是什么造成的呢？

**Comment by TDL3** [comment]
对了，我最近换了SSR提供商，或许跟这个有关？

**Comment by CGDF-Github** [comment]
要不你暂且换成原版SS测试几天

**Comment by TDL3** [comment]
行，那我用个3, 4天看看有没有这个问题

On Jan 9, 2019 00:15, "CGDF" <notifications@github.com> wrote:

要不你暂且换成原版SS测试几天

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CGDF-Github/SSD-Windows/issues/13#issuecomment-452356890>,
or mute the thread

**Comment by CGDF-Github** [comment]
[ShadowsocksD-0.1.8.zip](https://github.com/CGDF-Github/SSD-Windows/files/2737620/ShadowsocksD-0.1.8.zip)

哦刚刚翻了一下上游的历史，想起来了，原版4.1.2的确有这个BUG，因为我自己用的是基于原版4.1.3.1的0.1.8，所以复现不了，你要不试一试这个0.1.8

**Comment by TDL3** [comment]
好的，我试试看

**Comment by TDL3** [comment]
//貌似有一样的问题欸。但是这回它会自动修复，但是过一会它又会出现同样的问题，Log跟下方相同
[2019-01-11 18:06:39] Shadowsocks started (0.1.8)
[2019-01-11 18:06:39] 
=========================
Registered Encryptor Info
aes-128-cfb=>StreamOpenSSLEncryptor
aes-192-cfb=>StreamOpenSSLEncryptor
aes-256-cfb=>StreamOpenSSLEncryptor
aes-128-ctr=>StreamOpenSSLEncryptor
aes-192-ctr=>StreamOpenSSLEncryptor
aes-256-ctr=>StreamOpenSSLEncryptor
bf-cfb=>StreamOpenSSLEncryptor
camellia-128-cfb=>StreamOpenSSLEncryptor
camellia-192-cfb=>StreamOpenSSLEncryptor
camellia-256-cfb=>StreamOpenSSLEncryptor
rc4-md5=>StreamOpenSSLEncryptor
salsa20=>StreamSodiumEncryptor
chacha20=>StreamSodiumEncryptor
chacha20-ietf=>StreamSodiumEncryptor
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
=========================

[2019-01-11 18:06:41] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-11 18:06:41] System.Net.Sockets.SocketException (0x80004005): No such host is known
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
[2019-01-11 18:06:41] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)

**Comment by CGDF-Github** [comment]
看来已经是个成熟的软件了，已经学会自己修复了。。。

**Comment by CGDF-Github** [comment]
可以再麻烦你试几天原版SS吗。。。总觉得不像是我的锅。。。
以及，可以问下你用的是什么宽带吗？（难道是[长城/铁通]？）

**Comment by TDL3** [comment]
23333
好的，没问题，不过得下周才行
我用的是电信（校园网），不过处在同一网络下的SSR就很乖，没这么调皮

**Comment by TDL3** [comment]
原版ss 4.1.3.1版本我用了两天多了，没有发现这个问题。这两天我都有专门留意log，服务器timed out 还是会出现，但是没有出现Exception

会不会是服务器超时响应导致的呢？

**Comment by CGDF-Github** [comment]
使用的完全相同的配置和节点吗？

**Comment by TDL3** [comment]
对了，有一点需要说明，我们这个校园网会随机间歇性的卡顿，它不会影响看视频，但是玩游戏的话时不时延时会飙到1000多，过一两秒会恢复，不太确定是通过什么手段实现的

**Comment by TDL3** [comment]
是的

**Comment by TDL3** [comment]
同样的节点我在手机上用ssd从来没出过类似的问题

**Comment by CGDF-Github** [comment]
那看来windows上和原版ss的结果是一致的了。因为那个exception是检查版本更新的报错，和本issue无关

**Comment by CGDF-Github** [comment]
我是说log里的那个exception，不是弹窗弹出来的那个exception

**Comment by TDL3** [comment]
但这解释不了SSR可以正常工作啊QAQ

**Comment by CGDF-Github** [comment]
难道说SSR在校园网卡顿的时候还可以顽强工作？（话说问句，你用的加密方式是AEAD吗？）

**Comment by TDL3** [comment]
emmm，SSR我已经没法测试了QAQ，提供商终止对它的支持了，现在只剩SS/SSD和V2Ray了
我用的是chacha20，不知道属不属于AEAD算法

**Comment by TDL3** [comment]
而且SS也工作正常鸭

**Comment by CGDF-Github** [comment]
那还蛮奇怪的。。。emmmm你应该已经勾选了详细记录日志，所以现在的现象是【SSD偶尔会断开链接，然后又自动恢复，没有报错】。。。仅凭这个现象还蛮难判断的。。。
我再确认一下，SSD 0.1.8只有↓这个log吗？再上面提到的log还能再看见吗？
![image](https://user-images.githubusercontent.com/17256673/51117092-be8a7380-1847-11e9-87e9-81828e9114ff.png)

**Comment by TDL3** [comment]
这是之前能看到的部分
[log.txt](https://github.com/CGDF-Github/SSD-Windows/files/2755471/log.txt)

**Comment by TDL3** [comment]
大大加油鸭，我尝试看了看代码，CSharp真的爱莫能助了，Java我说不定还能帮上忙

**Comment by CGDF-Github** [comment]
你的0.1.8似乎没有勾选了详细记录日志，所以日志里几乎什么都没有。。。。

**Comment by CGDF-Github** [comment]
![image](https://user-images.githubusercontent.com/17256673/51119078-d87a8500-184c-11e9-8563-b1890c1efd59.png)
这个

**Comment by TDL3** [comment]
确实忘记开了。。。

**Comment by CGDF-Github** [comment]
那可能得麻烦你用0.1.8开一下详细记录日志，然后遇到“连接断开”的时候重新记录一下了。。。

**Comment by TDL3** [comment]
QAQ

**Comment by TDL3** [comment]
0.1.7的日志没价值吗？

**Comment by CGDF-Github** [comment]
说起来，我忘了问了，你说的“连接断开”是【连接墙外的通路被断开】还是【电脑整个网络都断开了（QQ都用不了了的那种）】？从0.1.7来看似乎是前面那种？

**Comment by CGDF-Github** [comment]
0.1.7上面显示断开原因是：No connection could be made because the target machine actively refused it
原因似乎是远程主机而不是本地才对
以及，你的服务器地址是【域名】还是【IP】？

**Comment by TDL3** [comment]
是的，断开时访问海外的网站有时候会无限加载，有时候会直接中断访问

**Comment by TDL3** [comment]
域名

**Comment by CGDF-Github** [comment]
那断开连接估计是你的主机切换DNS解析IP导致的吧。。。要不你ping了看看，ip和log里12月31号的时候、是否是一样。。。

**Comment by TDL3** [comment]
可是我不知道31号的IP地址鸭，之前注释里写的IP地址应该是服务器域名才对

**Comment by TDL3** [comment]
我翻到我之前录得一个视频，挺能说明问题的，你要不要看一下。但是里面有一些敏感信息，我不能发到Github上

**Comment by TDL3** [comment]
邮件你收到了吗

**Comment by CGDF-Github** [comment]
你似乎没有尝试切换节点？（不是重启）

**Comment by TDL3** [comment]
问题刚出现的几次我会去尝试，但是没什么效果，后面就没再尝试了

**Comment by CGDF-Github** [comment]
差不多
